const TECH_ICONS: Record<string, string> = {
  react: '⚛️',
  'next.js': '▲',
  nextjs: '▲',
  'next auth': '🔐',
  nextauth: '🔐',
  'node.js': '💚',
  nodejs: '💚',
  node: '💚',
  typescript: '🔷',
  ts: '🔷',
  javascript: '🟨',
  js: '🟨',
  python: '🐍',
  tailwind: '🎨',
  'tailwind css': '🎨',
  prisma: '🗄️',
  postgresql: '🐘',
  postgres: '🐘',
  mysql: '🐬',
  docker: '🐳',
  git: '🔀',
  github: '🐙',
  'github actions': '🤖',
  figma: '🎨',
  mongodb: '🍃',
  mongo: '🍃',
  redis: '🔴',
  graphql: '◈',
  aws: '☁️',
  firebase: '🔥',
  vue: '💚',
  svelte: '🧡',
  rust: '🦀',
  go: '🐹',
  java: '☕',
  kotlin: '🟣',
  swift: '🟠',
  php: '🐘',
  laravel: '⚡',
  django: '🎸',
  flask: '🌶️',
  rails: '💎',
  ruby: '💎',
  css: '🎨',
  html: '🌐',
  nuxt: '🟢',
  'react native': '📱',
  electron: '⚛️',
  stripe: '💳',
  supabase: '⚡',
  vercel: '▲',
  cloudinary: '☁️',
  resend: '📧',
  shadcn: '🧩',
  jest: '🃏',
  vitest: '🧪',
  playwright: '🎭',
  turborepo: '🐻',
  turbo: '🐻',
  pnpm: '📦',
  npm: '📦',
  yarn: '🧶',
  'framer motion': '✨',
  motion: '✨',
  zustand: '🐻',
  'react query': '🔄',
  tanstack: '🔄',
  trpc: '🔗',
  drizzle: '💧',
  planetscale: '🪐',
  planet: '🪐',
  discord: '💬',
  slack: '💬',
  linkedin: '💼',
  twitter: '🐦',
  x: '🐦',
  'vs code': '💻',
  vscode: '💻',
  postman: '📮',
  swagger: '📄',
  eslint: '📏',
  prettier: '✨',
  webpack: '📦',
  vite: '⚡',
  express: '⚡',
  fastify: '🚀',
  'material ui': '🎯',
  mui: '🎯',
  chakra: '⚡',
  bootstrap: '🅱️',
  jquery: '💲',
  sass: '💅',
  scss: '💅',
  redux: '🔄',
  'react router': '🧭',
  'react hook form': '📋',
  hookform: '📋',
  zod: '✅',
  'next-intl': '🌍',
  nextintl: '🌍',
  axios: '🌐',
  'styled components': '💅',
  'tailwindcss': '🎨',
  turbopack: '🐻',
  sentry: '👁️',
  datadog: '🐶',
  cloudflare: '☁️',
  'cloud flare': '☁️',
  digitalocean: '🌊',
  'digital ocean': '🌊',
  railway: '🚃',
  fly: '🪰',
  render: '🖥️',
  netlify: '🌐',
}

export function getTechIcon(name: string): string {
  const normalized = name.toLowerCase().trim().replace(/\s+/g, ' ')
  if (TECH_ICONS[normalized]) return TECH_ICONS[normalized]
  for (const [key, icon] of Object.entries(TECH_ICONS)) {
    if (normalized.includes(key) || key.includes(normalized)) return icon
  }
  return '🛠️'
}
